### ISSUE TITLE
App crashes due to CPU Limit

### ISSUE THREAD

**Issue by joeyv2** [gruijter/com.gruijter.zigbee2mqtt#38]
Hi,

The app crashes from time to time due to CPU Warning limit.
Can you check?
c3919a74-6300-4ca2-9453-ac762bfee260

Greetings

**Comment by gruijter** [comment]
```stdout:
        at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  statusCode: 400
} power_outage_memory true
2024-12-08T16:58:53.560Z [log] [ManagerDrivers] [Driver:device] [Device:93eb32b2-91d9-4c76-a4c9-9940ec2b49f7] Error: Invalid capability (homey:app:com.gruijter.zigbee2mqtt:power_outage_memory) value type. Expected: string. Got: boolean
    at Remote Process
    at HomeyClient.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54](mailto:/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50))
    at [/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZigbeeDevice.setCapabilityValue ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23))
    at ZigbeeDevice.setCapability (/app/drivers/Zigbee2MQTTDevice.js:256:12)
    at /app/drivers/Zigbee2MQTTDevice.js:390:22
    at Array.forEach ()
    at MqttClient.handleMessage (/app/drivers/Zigbee2MQTTDevice.js:370:34)
    at MqttClient.emit (node:events:529:35)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  statusCode: 400
} power_outage_memory true
2024-12-08T16:58:53.586Z [log] [ManagerDrivers] [Driver:device] [Device:d3f14c1f-6bb8-4b7f-a751-c190871edaf6] Error: Invalid capability (homey:app:com.gruijter.zigbee2mqtt:power_outage_memory) value type. Expected: string. Got: boolean
    at Remote Process
    at HomeyClient.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54](mailto:/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50))
    at [/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZigbeeDevice.setCapabilityValue ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23))
    at ZigbeeDevice.setCapability (/app/drivers/Zigbee2MQTTDevice.js:256:12)
    at /app/drivers/Zigbee2MQTTDevice.js:390:22
    at Array.forEach ()
    at MqttClient.handleMessage (/app/drivers/Zigbee2MQTTDevice.js:370:34)
    at MqttClient.emit (node:events:529:35)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  statusCode: 400
} power_outage_memory true
2024-12-08T16:58:57.263Z [log] [ManagerDrivers] [Driver:device] [Device:f7747db4-6b47-47e2-9d57-9bb3a2b8eb79] Error: Invalid capability (homey:app:com.gruijter.zigbee2mqtt:power_outage_memory) value type. Expected: string. Got: boolean
    at Remote Process
    at HomeyClient.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54](mailto:/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50))
    at [/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZigbeeDevice.setCapabilityValue ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23))
    at ZigbeeDevice.setCapability (/app/drivers/Zigbee2MQTTDevice.js:256:12)
    at /app/drivers/Zigbee2MQTTDevice.js:390:22
    at Array.forEach ()
    at MqttClient.handleMessage (/app/drivers/Zigbee2MQTTDevice.js:370:34)
    at MqttClient.emit (node:events:529:35)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  statusCode: 400
} power_outage_memory true
2024-12-08T16:58:57.263Z [log] [ManagerDrivers] [Driver:device] [Device:e4e331b1-22f2-44b0-9008-c600908e9a97] Error: Invalid capability (homey:app:com.gruijter.zigbee2mqtt:preset) value type. Expected: string. Got: number
    at Remote Process
    at HomeyClient.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54](mailto:/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50))
    at [/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZigbeeDevice.setCapabilityValue ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23))
    at ZigbeeDevice.setCapability (/app/drivers/Zigbee2MQTTDevice.js:256:12)
    at /app/drivers/Zigbee2MQTTDevice.js:390:22
    at Array.forEach ()
    at MqttClient.handleMessage (/app/drivers/Zigbee2MQTTDevice.js:370:34)
    at MqttClient.emit (node:events:529:35)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  statusCode: 400
} preset 1
2024-12-08T16:58:57.274Z [log] [ManagerDrivers] [Driver:device] [Device:5fa26051-596f-4f59-ab5d-b3f28f22a1f7] Error: Invalid capability (homey:app:com.gruijter.zigbee2mqtt:preset) value type. Expected: string. Got: number
    at Remote Process
    at HomeyClient.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54](mailto:/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54))
    at Object.emit ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50))
    at [/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:570:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ZigbeeDevice.setCapabilityValue ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:562:23))
    at ZigbeeDevice.setCapability (/app/drivers/Zigbee2MQTTDevice.js:256:12)
    at /app/drivers/Zigbee2MQTTDevice.js:390:22
    at Array.forEach ()
    at MqttClient.handleMessage (/app/drivers/Zigbee2MQTTDevice.js:370:34)
    at MqttClient.emit (node:events:529:35)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  statusCode: 400
} preset 1

    stderr:
    2024-12-06T18:40:06.663Z [err] [ManagerDrivers] [Driver:device] Error: Cannot find bridge device in Homey. Bridge needs to be added first!
    at /app/drivers/device/driver.js:37:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-06T21:01:27.730Z [err] [ManagerDrivers] [Driver:device] [Device:8629150f-f546-4047-a57b-5bfdc67070d4] Error: AL command not supported
    at ZigbeeDevice.setCommand (/app/drivers/Zigbee2MQTTDevice.js:297:86)
    at /app/drivers/Zigbee2MQTTDevice.js:451:24
    at ZigbeeDevice._onSetCapabilityValue ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:167:11](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:167:11))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-06T21:01:33.615Z [err] [ManagerDrivers] [Driver:device] [Device:8629150f-f546-4047-a57b-5bfdc67070d4] Error: OU command not supported
    at ZigbeeDevice.setCommand (/app/drivers/Zigbee2MQTTDevice.js:297:86)
    at /app/drivers/Zigbee2MQTTDevice.js:451:24
    at ZigbeeDevice._onSetCapabilityValue ([/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:167:11](mailto:/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:167:11))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-06T22:01:14.173Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected
2024-12-06T22:01:39.741Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected
2024-12-06T23:35:04.715Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected
2024-12-06T23:36:34.951Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected
2024-12-07T11:02:01.857Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected
2024-12-07T11:03:31.988Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected
2024-12-07T20:29:34.368Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached
2024-12-08T16:48:15.964Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected
2024-12-08T16:49:07.813Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Error: connect ECONNREFUSED 10.100.0.15:1883
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.100.0.15',
  port: 1883
}
2024-12-08T16:49:19.819Z [err] [ManagerDrivers] [Driver:bridge] [Device:a82d48df-c05a-4040-aebb-a91a99511c6b] Zigbee2MQTT bridge disconnected

⚠ The app has crashed.
CPU Warning Limit Reached

⚠ The app has crashed.
CPU Warning Limit Reached ```

**Comment by gruijter** [comment]
What device is this (link to https://www.zigbee2mqtt.io/devices )? 
I see `power_outage_memory`, where it expects `on` or `off` in stead of true/false...
and same goes for `preset` which should give a string, not a number.
